### ISSUE TITLE
Repo "badges" don't set cursor: pointer.

### ISSUE THREAD

**Issue by nubs** [guywithnose/pull-request-parser#27]
They don't appear to be clickable

**Comment by guywithnose** [comment]
Odd.  I get the cursor.  They should be getting it from the `.btn` class.

**Comment by nubs** [comment]
I get either the standard pointer or the text icon when hovering over various parts of the repo name.  The "Parse Pull Requests" and "Check all repos" buttons properly show a hand for me.

**Comment by guywithnose** [comment]
I see.  When you said badges I thought you meant the `X` (It has class `badge`).

**Comment by nubs** [comment]
ah my bad.  wrong terminology for the wrong thing :)
